export const CATEGORIES = [
  {
    id: 1,
    name: "Living Room",
    slug: "living-room",
    image: "https://images.pexels.com/photos/8135492/pexels-photo-8135492.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Elegant sofas, armchairs & coffee tables",
    count: 124,
  },
  {
    id: 2,
    name: "Bedroom",
    slug: "bedroom",
    image: "https://images.pexels.com/photos/8082562/pexels-photo-8082562.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Luxury beds, wardrobes & nightstands",
    count: 89,
  },
  {
    id: 3,
    name: "Dining Room",
    slug: "dining-room",
    image: "https://images.pexels.com/photos/7546218/pexels-photo-7546218.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Premium dining sets & bar stools",
    count: 67,
  },
  {
    id: 4,
    name: "Office",
    slug: "office",
    image: "https://images.pexels.com/photos/8082233/pexels-photo-8082233.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Executive desks, chairs & shelves",
    count: 45,
  },
  {
    id: 5,
    name: "Outdoor",
    slug: "outdoor",
    image: "https://images.pexels.com/photos/7546213/pexels-photo-7546213.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Weather-resistant garden furniture",
    count: 38,
  },
  {
    id: 6,
    name: "Decoration",
    slug: "decoration",
    image: "https://images.pexels.com/photos/8082243/pexels-photo-8082243.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    description: "Art, mirrors, lighting & accents",
    count: 201,
  },
];

export const PRODUCTS = [
  {
    id: 1,
    name: "Nordic Velvet Sofa",
    slug: "nordic-velvet-sofa",
    category: "Living Room",
    categorySlug: "living-room",
    price: 1299,
    oldPrice: 1899,
    rating: 4.8,
    reviewCount: 247,
    image: "https://images.pexels.com/photos/8135491/pexels-photo-8135491.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    images: [
      "https://images.pexels.com/photos/8135491/pexels-photo-8135491.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/8135492/pexels-photo-8135492.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/8082243/pexels-photo-8082243.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    colors: ["#8B7355", "#1C1C1C", "#E8E0D5", "#4A6B8A"],
    sizes: ["2-Seater", "3-Seater", "L-Shape"],
    stock: 15,
    isBestSeller: true,
    isNewArrival: false,
    isFeatured: true,
    material: "Velvet",
    brand: "LuxCraft",
    description: "Experience ultimate comfort with our Nordic Velvet Sofa. Crafted with premium velvet upholstery and solid oak legs, this sofa combines Scandinavian minimalism with exceptional comfort. Perfect for modern living spaces.",
    tags: ["sofa", "velvet", "nordic", "living room"],
  },
  {
    id: 2,
    name: "Marble Dining Table",
    slug: "marble-dining-table",
    category: "Dining Room",
    categorySlug: "dining-room",
    price: 2499,
    oldPrice: 3200,
    rating: 4.9,
    reviewCount: 183,
    image: "https://images.pexels.com/photos/14598479/pexels-photo-14598479.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    images: [
      "https://images.pexels.com/photos/14598479/pexels-photo-14598479.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/7546218/pexels-photo-7546218.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/5998031/pexels-photo-5998031.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    colors: ["#F5F0EB", "#2C2C2C", "#B8A99A"],
    sizes: ["4-Person", "6-Person", "8-Person"],
    stock: 8,
    isBestSeller: true,
    isNewArrival: false,
    isFeatured: true,
    material: "Marble & Steel",
    brand: "EliteHome",
    description: "A masterpiece of modern craftsmanship. Our Marble Dining Table features a genuine Carrara marble top with precision-cut steel legs. An investment piece that transforms every meal into a luxury experience.",
    tags: ["table", "marble", "dining", "luxury"],
  },
  {
    id: 3,
    name: "Executive Office Chair",
    slug: "executive-office-chair",
    category: "Office",
    categorySlug: "office",
    price: 899,
    oldPrice: 1299,
    rating: 4.7,
    reviewCount: 312,
    image: "https://images.pexels.com/photos/8082233/pexels-photo-8082233.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    images: [
      "https://images.pexels.com/photos/8082233/pexels-photo-8082233.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/8082224/pexels-photo-8082224.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    colors: ["#1C1C1C", "#5C4033", "#D4C5B0"],
    sizes: ["Standard", "XL"],
    stock: 22,
    isBestSeller: false,
    isNewArrival: true,
    isFeatured: true,
    material: "Full-Grain Leather",
    brand: "ComfortPro",
    description: "Command your workspace with our Executive Office Chair. Premium full-grain leather, ergonomic lumbar support, and customizable armrests make this the ultimate seating solution for professionals.",
    tags: ["chair", "office", "leather", "ergonomic"],
  },
  {
    id: 4,
    name: "Platform Bed Frame",
    slug: "platform-bed-frame",
    category: "Bedroom",
    categorySlug: "bedroom",
    price: 1799,
    oldPrice: 2400,
    rating: 4.8,
    reviewCount: 156,
    image: "https://images.pexels.com/photos/7546276/pexels-photo-7546276.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    images: [
      "https://images.pexels.com/photos/7546276/pexels-photo-7546276.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/8082562/pexels-photo-8082562.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/8082217/pexels-photo-8082217.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    colors: ["#4A3728", "#1C1C1C", "#E8E0D5"],
    sizes: ["Queen", "King", "California King"],
    stock: 11,
    isBestSeller: true,
    isNewArrival: false,
    isFeatured: true,
    material: "Solid Walnut",
    brand: "SleepLux",
    description: "Wake up in luxury with our Platform Bed Frame. Crafted from solid American walnut with a hand-rubbed oil finish, featuring built-in LED ambient lighting and hidden storage compartments.",
    tags: ["bed", "bedroom", "walnut", "platform"],
  },
  {
    id: 5,
    name: "Accent Lounge Chair",
    slug: "accent-lounge-chair",
    category: "Living Room",
    categorySlug: "living-room",
    price: 649,
    oldPrice: 899,
    rating: 4.6,
    reviewCount: 198,
    image: "https://images.pexels.com/photos/8082242/pexels-photo-8082242.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    images: [
      "https://images.pexels.com/photos/8082242/pexels-photo-8082242.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/8082243/pexels-photo-8082243.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    colors: ["#C5A882", "#1C1C1C", "#7B9EA6", "#8B6F5E"],
    sizes: ["Standard"],
    stock: 30,
    isBestSeller: false,
    isNewArrival: true,
    isFeatured: true,
    material: "Boucle",
    brand: "LuxCraft",
    description: "Add a sculptural statement to any room with our Accent Lounge Chair. The plush boucle upholstery and curved silhouette create a perfect blend of comfort and artistry.",
    tags: ["chair", "lounge", "accent", "boucle"],
  },
  {
    id: 6,
    name: "Modern Bookshelf",
    slug: "modern-bookshelf",
    category: "Office",
    categorySlug: "office",
    price: 799,
    oldPrice: 1100,
    rating: 4.5,
    reviewCount: 89,
    image: "https://images.pexels.com/photos/5511099/pexels-photo-5511099.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    images: [
      "https://images.pexels.com/photos/5511099/pexels-photo-5511099.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/8082224/pexels-photo-8082224.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    colors: ["#8B7355", "#1C1C1C", "#E8E0D5"],
    sizes: ["4-Tier", "6-Tier"],
    stock: 18,
    isBestSeller: false,
    isNewArrival: true,
    isFeatured: false,
    material: "Oak & Metal",
    brand: "EliteHome",
    description: "A functional yet stunning piece for your home or office. Our Modern Bookshelf features solid oak shelves with powder-coated steel frame, offering the perfect balance of style and storage.",
    tags: ["shelf", "bookshelf", "office", "oak"],
  },
  {
    id: 7,
    name: "Luxury Sectional Sofa",
    slug: "luxury-sectional-sofa",
    category: "Living Room",
    categorySlug: "living-room",
    price: 3499,
    oldPrice: 4800,
    rating: 4.9,
    reviewCount: 421,
    image: "https://images.pexels.com/photos/7174113/pexels-photo-7174113.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    images: [
      "https://images.pexels.com/photos/7174113/pexels-photo-7174113.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/8135492/pexels-photo-8135492.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    colors: ["#D4C5B0", "#5C4033", "#1C1C1C", "#6B8A7B"],
    sizes: ["3-Piece", "4-Piece", "5-Piece"],
    stock: 5,
    isBestSeller: true,
    isNewArrival: false,
    isFeatured: true,
    material: "Italian Leather",
    brand: "LuxCraft",
    description: "Our signature Luxury Sectional Sofa redefines living room elegance. Hand-stitched Italian leather, goose-down cushions, and solid mahogany legs create an unparalleled seating experience.",
    tags: ["sofa", "sectional", "leather", "luxury"],
  },
  {
    id: 8,
    name: "Minimalist Coffee Table",
    slug: "minimalist-coffee-table",
    category: "Living Room",
    categorySlug: "living-room",
    price: 549,
    oldPrice: 749,
    rating: 4.7,
    reviewCount: 134,
    image: "https://images.pexels.com/photos/7546213/pexels-photo-7546213.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    images: [
      "https://images.pexels.com/photos/7546213/pexels-photo-7546213.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/8082243/pexels-photo-8082243.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    colors: ["#C8B89A", "#1C1C1C", "#E8E0D5"],
    sizes: ["Small", "Medium", "Large"],
    stock: 25,
    isBestSeller: false,
    isNewArrival: true,
    isFeatured: false,
    material: "Travertine & Brass",
    brand: "EliteHome",
    description: "A statement piece for the modern home. Our Minimalist Coffee Table features a genuine travertine stone top with brushed brass legs, bringing natural elegance to your living space.",
    tags: ["table", "coffee table", "travertine", "minimalist"],
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Alexandra Chen",
    role: "Interior Designer",
    avatar: "AC",
    rating: 5,
    comment: "Absolutely stunning quality! The Nordic Velvet Sofa I ordered exceeded all my expectations. The craftsmanship is impeccable and delivery was seamless. Will definitely be recommending to all my clients.",
    product: "Nordic Velvet Sofa",
    date: "2 weeks ago",
  },
  {
    id: 2,
    name: "Marcus Williams",
    role: "Architect",
    avatar: "MW",
    rating: 5,
    comment: "The Marble Dining Table is a true masterpiece. It's become the centerpiece of our home and every guest comments on it. Premium quality that justifies every penny.",
    product: "Marble Dining Table",
    date: "1 month ago",
  },
  {
    id: 3,
    name: "Sofia Rodriguez",
    role: "Homeowner",
    avatar: "SR",
    rating: 5,
    comment: "Luxora has completely transformed my living space. The attention to detail in every piece is remarkable. Fast shipping and excellent customer service made the experience perfect.",
    product: "Platform Bed Frame",
    date: "3 weeks ago",
  },
  {
    id: 4,
    name: "James Thompson",
    role: "CEO",
    avatar: "JT",
    rating: 4,
    comment: "The Executive Office Chair has been a game-changer for my productivity. Premium leather, perfect lumbar support, and looks absolutely professional in my home office.",
    product: "Executive Office Chair",
    date: "1 week ago",
  },
];
